FORMAT: 1A
HOST: http://api.zhihuazhang.net/magokoro

# mogokoro

まごころAPI.

# Group 认证

## Auth [/login]

### 登陆 [POST]

+ Request (application/json)

            {
                "uid": "zhz821",
                "password": "123"
            }

+ Response 200 (application/json)
    + Body

            {
                "user": {
                            "_id" : "57fc366c9a04201a98836126"
                            "uid": "zhz821",
                            "name": "張志華",
                            "createdAt": "2016-12-01T08:40:51.620Z",
                            "gender": 0,
                            "birthday": "1982/01/16",
                            "avatar": "xxxx.png",
                            "inviting": [
                                        {"uid": "abc"},
                                        {"uid": "def"}
                                        ]
                        },
                "accessToken": "abcdefghijklmn"
            }

## Logout [/logout]

### 注销 [POST]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Attributes

        + device: xxxx (required) - 注销设备的id，需要删除以停止接收通知

+ Response 200


# Group 用户

## Users [/users]

+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126"
        "uid": "zhz821",
        "name": "張志華",
        "createdAt": "2016-12-01T08:40:51.620Z",
        "gender": 0,
        "birthday": "1982/01/16",
        "avatar": "xxxx.png",
        "inviting": [
                    {"uid": "abc"},
                    {"uid": "def"}
                    ],
        "invited": [
                    {"uid": "ghi"},
                    {"uid": "jkl"}
                    ],
        "friend": [
                    {"uid": "aaa"}
                    ]
    }
    ```

### 注册新用户 [POST]

+ Request (application/json)

    + Attributes

        + uid: zhz821 (required)
        + password: 123(required)
        + name: 張志華(required)
        + gender: 0(required)
        + birthday: 1982/1/16(required)

+ Response 201 (application/json)
    + Body

            {
                "user": {
                    "_id" : "57fc366c9a04201a98836126",
                    "uid": "zhz821",
                    "name": "張志華",
                    "createdAt": "2016-12-01T08:40:51.620Z",
                    "gender": 0,
                    "birthday": "1982/01/16"
                },
                "accessToken": "abcdefghijklmn"
            }
            
+ Response 409 (application/json)
    + Body

            {
                "message": "IDがすでに登録済みです。"
            }

## Me [/user]

+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126"
        "uid": "zhz821",
        "name": "張志華",
        "createdAt": "2016-12-01T08:40:51.620Z",
        "gender": 0,
        "birthday": "1982/01/16",
        "avatar": "xxxx.png",
        "inviting": [
                    {"uid": "abc"},
                    {"uid": "def"}
                    ],
        "invited": [
                    {"uid": "ghi"},
                    {"uid": "jkl"}
                    ],
        "friend": [
                    {"uid": "aaa"}
                    ]
    }
    ```

### 取得自己信息 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200

    [Me][]

### 更新自己信息 [PATCH]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Body

            {
                "name": "Nakata"
            }
            
+ Response 200

    [Me][]

## Invite [/user/inviting/{uid}]

+ Parameters
    + uid: `rtx` (string) - 被邀请者的uid.

### 发送好友邀请 [PUT]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200
    [Me][]

## Friend [/user/friend/{uid}]

+ Parameters
    + uid: `rtx` (string) - 要接受好友邀请的用户的uid.

### 接受好友邀请 [PUT]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200
    [Me][]

## User [/users/{uid}]

+ Parameters
    + uid: `zhz821` (string) - 用户的uid.
    
+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126",
        "uid": "zhz821",
        "name": "張志華",
        "avatar": "xxxx.png",
        "createdAt": "2016-12-01T08:40:51.620Z",
        "gender": 0,
        "birthday": "1982/01/16",
        "status": "inviting"
    }
    ```
### 用户信息取得 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200
    [User][]

# Group 消息

## Message [/messages/{mid}]

+ Parameters
    + mid: `123456` (string) - 消息的id.

+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126",
        "event": "誕生日",
        "content": "おめでとうございます。",
        "createdAt": "2016-12-01T08:40:51.620Z",
        "from": {uid: "zhz821"},
        "to": {uid: "rtx"},
        "photo": "UAwJnBIBw8R_T7jy6S9RSV_M.JPEG",
        "video": {"thumbnail": "UAwJnBIBw8R_T7jy6S9RSV_M.PNG", "url": "kFZejqx8Zpzse9TBWJ0mYGou.MOV"},
        "replies": [
                        {
                            "content": "ありがとうございます。", 
                            "from": {uid: "zhz821"},
                            "to": {uid: "rtx"}
                        }
                    ]
    }
    ```

### 取得消息 [GET]

+ Response 200

    [Message][]

## Messages [/messages]

### 发送消息 [PUT]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Attributes

        + event: 誕生日 (required)
        + content: おめでとうございます。(required)
        + name: 張志華(required)
        + uid: rtx(required) - 收件人uid
        + photo: 1111 - 图片数据
        + video: 1010 - 视频数据

+ Response 201

    [Message][]

## Reply [/messages/{mid}/replies]

+ Parameters
    + mid: `123456` (string) - 消息的id.

### 回复消息 [PATCH]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Attributes

        + content: ありがとうございます。(required)

+ Response 200

    [Message][]

# Group 事件

## Events Collection [/events]

### 事件一览 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200 (application/json)

    + Body

            [
                {
                    "_id": "5726ac024ff978af01400b57",
                    "type": "inviting",
                    "from": {
                        "uid" : "test04",
                        "name" : "Test04",
                        "avatar": "xxxx.png"
                    },
                    "to": {
                        "uid" : "test05",
                        "name" : "Test05",
                        "avatar": "xxxx.png"
                    },
                    "createdAt": "2016-12-01T08:40:51.620Z"
                },
                {
                    "_id": "5726ac024ff978af01400b57",
                    "type": "message",
                    "from": {
                        "uid" : "test04",
                        "name" : "Test04",
                        "avatar": "xxxx.png"
                    },
                    "to": {
                        "uid" : "test05",
                        "name" : "Test05",
                        "avatar": "xxxx.png"
                    },
                    "event": "圣诞节",
                    "mid": "m12345678",
                    "createdAt": "2016-12-01T08:40:51.620Z"
                }
            ]

# Group 设备

## devices [/devices]

### 上传设备 [POST]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Attributes

        + deviceId: xxxx (required) - 设备ID

+ Response 200
