FORMAT: 1A
HOST: http://api.zhihuazhang.net/magokoro

# mogokoro

まごころAPI.

# Group Auth

## Auth [/auth/login]

### 登陆 [POST]

+ Request (application/json)

        {
            "uid": "zhz821",
            "password": "123"
        }
        
+ Response 200 (application/json)
    + Body

            {
                "user": {
                            "_id" : "57fc366c9a04201a98836126"
                            "uid": "zhz821",
                            "name": "張志華",
                            "created_at": "2016-12-01T08:40:51.620Z",
                            "gender": 0,
                            "birthday": "1982/01/16",
                            "invites": [
                                        {"uid": "abc", "name": "ABC"},
                                        {{"uid": "def", "name": "DEF"}
                                        ]
                        },
                "accessToken": "abcdefghijklmn"
            }

# Group Users

## Me [/api/user]

+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126"
        "uid": "zhz821",
        "name": "張志華",
        "created_at": "2016-12-01T08:40:51.620Z",
        "gender": 0,
        "birthday": "1982/01/16",
        "inviting": [
                    {"uid": "abc", "name": "ABC"},
                    {"uid": "def", "name": "DEF"}
                    ],
        "invited": [
                    {"uid": "ghi", "name": "GHI"},
                    {"uid": "jkl", "name": "JKL"}
                    ],
        "friend": [
                    {"uid": "aaa", "name": "AAA"}
                    ]
    }
    ```

### 取得自己信息 [GET]

+ Request 

    + Headers
    
            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200

    [Me][]

### 更新自己信息 [PATCH]

+ Request 

    + Headers
    
            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
            
    + Body
    
            {
                "name": "Nakata"
            }
            
+ Response 200

    [Me][]
    
## Invite [/api/user/inviting/{uid}]

+ Parameters
    + uid: `rtx` (string) - 被邀请者的uid.

### 发送好友邀请 [PUT]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200
    [Me][]

## User [/api/users/{uid}]

+ Parameters
    + uid: `zhz821` (string) - 用户的uid.
    
+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126",
        "uid": "zhz821",
        "name": "張志華",
        "created_at": "2016-12-01T08:40:51.620Z",
        "gender": 0,
        "birthday": "1982/01/16",
        "status": "inviting"
    }
    ```
### 用户信息取得 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200
    [User][]

## Users Collection [/users]

### 注册新用户 [POST]

+ Request (application/json)
    + Body

            {
                "uid": "zhz821",
                "password": "123",
                "name": "張志華",
                "gender": 0,
                "birthday": "1982/01/16"
            }

+ Response 201 (application/json)
    + Body

            {
                "user": {
                    "_id" : "57fc366c9a04201a98836126",
                    "uid": "zhz821",
                    "name": "張志華",
                    "createdAt": "2016-12-01T08:40:51.620Z",
                    "gender": 0,
                    "birthday": "1982/01/16"
                },
                "token": "abcdefghijklmn"
            }
            
+ Response 409 (application/json)
    + Body

                {
                    "message": "IDがすでに登録済みです。"
                }