FORMAT: 1A
HOST: http://api.zhihuazhang.net/magokoro

# mogokoro

まごころAPI.

# Group 认证

## Auth [/login]

### 登陆 [POST]

+ Request (application/json)

            {
                "uid": "zhz821",
                "password": "123"
            }

+ Response 200 (application/json)
    + Body

            {
                "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9",
                "user": {
                    "_id": "581ddc4989fc2ac44f365f45",
                    "name": "ouyou1",
                    "gender": 1,
                    "birthday": "2010年01月01日",
                    "uid": "wangyao",
                    "createdAt": "2016-11-05T13:19:05.683Z",
                    "inviting": [
                        {
                            "uid": "liuweilin"
                        }
                    ],
                    "friends": [
                        {
                            "_id": "581d393a14aa5b031dad9540",
                            "name": "ふみ",
                            "uid": "zhz110501",
                            "avatar": "dhod1keUd7te-uvN9YSbY00E.png"
                        },
                        {
                            "_id": "581d3d7d14aa5b031dad9541",
                            "name": "こうよう",
                            "uid": "zhz110502"
                        }
                    ],
                    "invited": [
                        {
                            "uid": "112101"
                        },
                        {
                            "uid": "112801"
                        }
                    ],
                    "avatar": "JjaDbRAMoZm0s90olA4VREL6.png"
                }
            }
+ Response 401 (application/json)
    + Body

            {
                "status": 401,
                "message": "IDとパスワードが一致しません。"
            }

## Logout [/logout]

### 注销 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200


# Group 用户

## Users [/users]

+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126"
        "uid": "zhz821",
        "name": "張志華",
        "createdAt": "2016-12-01T08:40:51.620Z",
        "gender": 0,
        "birthday": "1982/01/16",
        "avatar": "xxxx.png",
        "inviting": [
                    {"uid": "abc"},
                    {"uid": "def"}
                    ],
        "invited": [
                    {"uid": "ghi"},
                    {"uid": "jkl"}
                    ],
        "friend": [
                    {"uid": "aaa"}
                    ]
    }
    ```

### 注册新用户 [POST]

+ Request (application/json)

    + Attributes

        + uid: zhz821 (required)
        + password: 123(required)
        + name: 張志華(required)
        + gender: 0(required)
        + birthday: 1982/1/16(required)

+ Response 200 (application/json)
    + Body

        {
            "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9",
            "user": {
                "_id": "581ddc4989fc2ac44f365f45",
                "name": "ouyou1",
                "gender": 1,
                "birthday": "2010年01月01日",
                "uid": "wangyao",
                "createdAt": "2016-11-05T13:19:05.683Z"
            }
        }

            
+ Response 409 (application/json)
    + Body

            {
                "status": 409,
                "message": "IDがすでに登録済みです。"
            }

### 用户信息取得 [GET]

+ Parameters
    + uid: `zhz821` (string) - 用户的uid.

        For example: `users/zhz821`

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200 (application/json)
    + Body
            {
                "uid": "zhz821",
                "name": "張志華",
                "avatar": "xxxx.png",
                "status": "inviting"
            }

### 取得多个用户信息 [GET]

+ Parameters

    + uids (required, string) ... 用户的uid. 可以指定多个

        For example: `users?uids[]=wangyao&uids[]=zhz821`

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ response 200 (application/json)
    + Body

        [{
            "_id": "581ddc4989fc2ac44f365f45",
            "name": "ouyou1",
            "uid": "wangyao",
            "avatar": "JjaDbRAMoZm0s90olA4VREL6.png"
        }, {
            "_id": "583c1b593e3fdbaffdf89c2a",
            "name": "張志華",
            "uid": "zhz821"
        }]

## Me [/user]

+ Model (application/json)

    ```js
    {
        "_id": "581ddc4989fc2ac44f365f45",
        "name": "ouyou1",
        "gender": 1,
        "birthday": "2010年01月01日",
        "uid": "wangyao",
        "createdAt": "2016-11-05T13:19:05.683Z",
        "inviting": [
            {
                "uid": "liuweilin"
            }
        ],
        "friends": [
            {
                "_id": "581d393a14aa5b031dad9540",
                "name": "ふみ",
                "uid": "zhz110501",
                "avatar": "dhod1keUd7te-uvN9YSbY00E.png"
            },
            {
                "_id": "581d3d7d14aa5b031dad9541",
                "name": "こうよう",
                "uid": "zhz110502"
            }
        ],
        "invited": [
            {
                "uid": "112101"
            },
            {
                "uid": "112801"
            }
        ],
        "avatar": "JjaDbRAMoZm0s90olA4VREL6.png"
    }
    ```

### 取得自己信息 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200

    [Me][]

### 更新自己信息 [PATCH]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Body

            {
                "name": "Nakata"
            }
            
+ Response 200

    [Me][]

## 头像 [/user/avatar]

### 更新头像 [PATCH]

+ Request (multipart/form-data; boundary=alamofire.boundary.d1d87f727c4b2819)

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Body

            --alamofire.boundary.d1d87f727c4b2819
            Content-Disposition: form-data; name="img"; filename="avatar.png"
            Content-Type: image/png


            /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
            HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
            MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
            AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
            AAAAAAAAAAAAAAAA
            --alamofire.boundary.d1d87f727c4b2819--

### 删除头像 [DELETE]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200

## Invite [/user/inviting/{uid}]

+ Parameters
    + uid: `rtx` (string) - 被邀请者的uid.

### 发送好友邀请 [PUT]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200
    [Me][]

## Friend [/user/friend/{uid}]

+ Parameters
    + uid: `rtx` (string) - 要接受好友邀请的用户的uid.

### 接受好友邀请 [PUT]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200
    [Me][]

# Group 消息

## Message [/messages/{mid}]

+ Parameters
    + mid: `123456` (string) - 消息的id.

+ Model (application/json)

    ```js
    {
        "_id" : "57fc366c9a04201a98836126",
        "event": "誕生日",
        "content": "おめでとうございます。",
        "createdAt": "2016-12-01T08:40:51.620Z",
        "from": {uid: "zhz821"},
        "to": {uid: "rtx"},
        "photo": "UAwJnBIBw8R_T7jy6S9RSV_M.JPEG",
        "video": {"thumbnail": "UAwJnBIBw8R_T7jy6S9RSV_M.PNG", "url": "kFZejqx8Zpzse9TBWJ0mYGou.MOV"},
        "replies": [
                        {
                            "content": "ありがとうございます。", 
                            "from": {uid: "zhz821"},
                            "to": {uid: "rtx"}
                        }
                    ]
    }
    ```

### 取得消息 [GET]

+ Response 200

    [Message][]

## Messages [/messages/{uid}]

+ Parameters
    + uid: `zhz821` (string) - 消息接收方的uid.

### 发送消息 [POST]

+ Request (application/json)

    + Headers
            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Body        
        {
            "content": "Q",
            "subject": "letter"
        }

+ Response 200 (application/json)

    {
        "content": "Q",
        "subject": "letter",
        "createdAt": "2016-11-29T03:50:12.982Z",
        "from": {
            "name": "112801",
            "uid": "112801",
            "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
        },
        "to": {
            "name": "Nakata",
            "uid": "nakata"
        },
        "_id": "583cfaf455ac51b26f534ba8",
        "createdDay": "2016年11月29日"
    }

## Reply [/messages/{mid}/reply]

+ Parameters
    + mid: `123456` (string) - 消息的id.

### 回复文本消息 [PUT]

+ Request (application/json)

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Body
        {
            "content": "q"
        }

+ Response 200 (application/json)

    {
        "_id": "583cfac255ac51b26f534ba4",
        "content": "Qwert ",
        "subject": "letter",
        "createdAt": "2016-11-29T03:49:22.772Z",
        "from": {
            "name": "112801",
            "uid": "112801",
            "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
        },
        "to": {
            "name": "Nakata",
            "uid": "nakata"
        },
        "replies": [{
            "sender": {
                "name": "112801",
                "uid": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
            },
            "content": "q",
            "type": "text",
            "createdAt": "2016-11-29T03:49:26.254Z"
        }],
        "createdDay": "2016年11月29日"
    }

## Reply Image [/messages/{mid}/image]

+ Parameters
    + mid: `123456` (string) - 消息的id.

### 回复图片消息 [PUT]

+ Request (multipart/form-data; boundary=alamofire.boundary.d1d87f727c4b2819)

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Body

            --alamofire.boundary.d1d87f727c4b2819
            Content-Disposition: form-data; name="img"; filename="image.png"
            Content-Type: image/png


            /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
            HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
            MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
            AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
            AAAAAAAAAAAAAAAA
            --alamofire.boundary.d1d87f727c4b2819--

+ Response 200 (application/json)

    + Body
        {
            "_id": "583cfac255ac51b26f534ba4",
            "content": "Qwert ",
            "subject": "letter",
            "createdAt": "2016-11-29T03:49:22.772Z",
            "from": {
                "name": "112801",
                "uid": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
            },
            "to": {
                "name": "Nakata",
                "uid": "nakata"
            },
            "replies": [{
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "content": "q",
                "type": "text",
                "createdAt": "2016-11-29T03:49:26.254Z"
            }, {
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "type": "image",
                "image": "9irRAjXFqz1A4F7JlVKw9GrM.png",
                "createdAt": "2016-11-29T03:49:37.968Z"
            }],
            "createdDay": "2016年11月29日"
        }

## Reply Video [/messages/{mid}/video]

+ Parameters
    + mid: `123456` (string) - 消息的id.

### 回复视频消息 [PUT]

+ Request (multipart/form-data; boundary=alamofire.boundary.d1d87f727c4b2819)

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Body

            --alamofire.boundary.d1d87f727c4b2819
            Content-Disposition: form-data; name="video"; filename="xxxxx.mp4"
            Content-Type: video/mp4


            /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
            HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
            MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
            AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
            AAAAAAAAAAAAAAAA
            --alamofire.boundary.d1d87f727c4b2819--

+ Response 200 (application/json)

    + Body
        {
            "_id": "583cfac255ac51b26f534ba4",
            "content": "Qwert ",
            "subject": "letter",
            "createdAt": "2016-11-29T03:49:22.772Z",
            "from": {
                "name": "112801",
                "uid": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
            },
            "to": {
                "name": "Nakata",
                "uid": "nakata"
            },
            "replies": [{
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "content": "q",
                "type": "text",
                "createdAt": "2016-11-29T03:49:26.254Z"
            }, {
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "type": "image",
                "image": "9irRAjXFqz1A4F7JlVKw9GrM.png",
                "createdAt": "2016-11-29T03:49:37.968Z"
            }, {
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "type": "video",
                "image": "09429490-b5e7-11e6-9f16-957be1685457.png",
                "video": "CF_elLYz8maZsMmkV0OHWc4N.mp4",
                "createdAt": "2016-11-29T03:50:58.501Z"
            }],
            "createdDay": "2016年11月29日"
        }

## Reply Pressent [/messages/{mid}/present/{pid}]

+ Parameters
    + mid: `123456` (string) - 消息的id.
    + pid: `qwert` (string) - 礼物的id.

### 回复物品链接消息 [PUT]

+ Request (application/json)

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200 (application/json)

    + Body 
        {
            "_id": "583cfac255ac51b26f534ba4",
            "content": "Qwert ",
            "subject": "letter",
            "createdAt": "2016-11-29T03:49:22.772Z",
            "from": {
                "name": "112801",
                "uid": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
            },
            "to": {
                "name": "Nakata",
                "uid": "nakata"
            },
            "replies": [{
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "content": "q",
                "type": "text",
                "createdAt": "2016-11-29T03:49:26.254Z"
            }, {
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "type": "image",
                "image": "9irRAjXFqz1A4F7JlVKw9GrM.png",
                "createdAt": "2016-11-29T03:49:37.968Z"
            }, {
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "type": "video",
                "image": "09429490-b5e7-11e6-9f16-957be1685457.png",
                "video": "CF_elLYz8maZsMmkV0OHWc4N.mp4",
                "createdAt": "2016-11-29T03:50:58.501Z"
            }, {
                "sender": {
                    "name": "112801",
                    "uid": "112801",
                    "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
                },
                "present": {
                    "title": "mac",
                    "link": "apple.com",
                    "price": "12345",
                    "image": "xx.jpg",
                    "gid": "12001814c0856dc623a11b9d2a1cb03c"
                },
                "type": "present",
                "createdAt": "2016-11-29T05:38:55.899Z"
            }],
            "createdDay": "2016年11月29日"
        }

# Group 事件

## Events Collection [/events]

### 事件一览 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200 (application/json)

    + Body

            [{
              "_id": "583cfb2255ac51b26f534bab",
              "type": "video",
              "message": {
                "_id": "583cfac255ac51b26f534ba4"
              },
              "from": {
                "uid": "112801",
                "name": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
              },
              "to": {
                "uid": "nakata",
                "name": "Nakata",
                "avatar": null
              },
              "subject": "letter",
              "createdAt": "2016-11-29T03:50:58.509Z",
              "read": 0
            }, {
              "_id": "583cfad155ac51b26f534ba7",
              "type": "image",
              "message": {
                "_id": "583cfac255ac51b26f534ba4"
              },
              "from": {
                "uid": "112801",
                "name": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
              },
              "to": {
                "uid": "nakata",
                "name": "Nakata",
                "avatar": null
              },
              "subject": "letter",
              "createdAt": "2016-11-29T03:49:37.983Z",
              "read": 1
            }, {
              "_id": "583c28862c4fdcb6d69a6ce1",
              "type": "present",
              "message": {
                "_id": "583c2521aec5c3b68697c684"
              },
              "from": {
                "uid": "112801",
                "name": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
              },
              "to": {
                "uid": "nakata",
                "name": "Nakata",
                "avatar": null
              },
              "subject": "letter",
              "createdAt": "2016-11-28T12:52:22.655Z",
              "read": 0
            }, {
              "_id": "583c25fc9087d7b6a29c9486",
              "type": "reply",
              "message": {
                "_id": "583c2521aec5c3b68697c684"
              },
              "from": {
                "uid": "112801",
                "name": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
              },
              "to": {
                "uid": "nakata",
                "name": "Nakata",
                "avatar": null
              },
              "subject": "letter",
              "createdAt": "2016-11-28T12:41:32.945Z",
              "read": 0
            }, {
              "_id": "583c2521aec5c3b68697c685",
              "type": "message",
              "message": {
                "_id": "583c2521aec5c3b68697c684"
              },
              "from": {
                "uid": "112801",
                "name": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
              },
              "to": {
                "uid": "nakata",
                "name": "Nakata",
                "avatar": null
              },
              "subject": "letter",
              "createdAt": "2016-11-28T12:37:53.215Z",
              "read": 0
            }, {
              "_id": "583c221e2db605b64a7a1abf",
              "type": "agree",
              "from": {
                "uid": "112801",
                "name": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
              },
              "to": {
                "uid": "nakata",
                "name": "Nakata",
                "avatar": null
              },
              "createdAt": "2016-11-28T12:25:02.521Z",
              "read": 0
            }, {
              "_id": "583c22082db605b64a7a1abe",
              "type": "inviting",
              "from": {
                "uid": "nakata",
                "name": "Nakata",
                "avatar": null
              },
              "to": {
                "uid": "112801",
                "name": "112801",
                "avatar": "mGfl1H8OTmPtA32kDuB0suDs.png"
              },
              "createdAt": "2016-11-28T12:24:40.596Z",
              "read": 1
            }]

## read [/events/{id}/read]

+ Parameters
    + id: `123456` (string) - 消息的id.

### 即读 [PATCH]


+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200

# Group 礼物

## presents [/category/{id}/presents]

+ Parameters
    + id: `123456` (string) - 礼物类别id.

### 取得某一分类的礼物 [GET]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

+ Response 200 (application/json)
        [{
            "title": "mac",
            "link": "apple.com",
            "price": "12345",
            "image": "xx.jpg",
            "gid": "12001814c0856dc623a11b9d2a1cb03c"
        }, {
            "title": "thinkpad",
            "link": "ibm.com",
            "price": "9999",
            "image": "ttt.jpg",
            "gid": "86d7102822ef859ba01e53c60e0d9c55"
        }, {
            "title": "ps3",
            "link": "ps3.com",
            "price": "8888",
            "image": "xxx.jpg",
            "gid": "3e9ccd4fa22bf811576e358c3546ec82"
        }, {
            "title": "1111",
            "link": "1111",
            "price": "1111",
            "image": "1111",
            "gid": "e628fa16f36b8949ca1940903ced854b"
        }]

# Group 设备

## devices [/devices]

### 上传设备 [POST]

+ Request 

    + Headers

            authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

    + Attributes

        + deviceId: xxxx (required) - 设备ID

+ Response 200
